version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  pyspark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - Data-Engineering/pyspark:/home/jovyan/work
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/jovyan/work/path_to_service_account.json

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - Data-Engineering/postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/

  dbt:
    image: dbtlabs/dbt:latest
    volumes:
      - Data-Engineering/dbt:/dbt
    environment:
      DBT_PROFILES_DIR: /dbt
      GOOGLE_APPLICATION_CREDENTIALS: /dbt/path_to_service_account.json

  airflow:
    image: apache/airflow:latest
    environment:
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres/mydb
      - AIRFLOW__CELERY__BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://postgres:postgres@postgres/mydb
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

volumes:
  pyspark_data:
  postgres_data:
  dbt_data:
