name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'my_bigquery_connection'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  monthly_payments:
    materialized: view
    sql: monthly_payments.sql
    
  payment_analytics:
    materialized: view
    sql: payment_analytics.sql
