
version: 2

models:
  - name: monthly_payments
    description: "View containing monthly payments analytics."
    columns:
      - name: Month
        description: "The month when the loan was repaid."
        tests:
          - unique
      - name: TotalLoansPaid
        description: "Total number of loans paid in the month."
      - name: TotalAmountPaid
        description: "Total amount repaid in the month."

  - name: payment_analytics
    description: "View containing payment analytics."
    columns:
      - name: PaidOnTime
        description: "Indicates whether the payment was made on time (Yes/No)."
        tests:
          - accepted_values: ['Yes', 'No']
      - name: LateTime
        description: "Time taken for payment after expected repayment date."
        tests:
          - accepted_values: ['< 7', '> 7']
      - name: PaidMonth
        description: "The month when the payment was made."
        tests:
          - unique
      - name: AmountPaid
        description: "Total amount paid for the loans in the month."
      - name: DefaultStatus
        description: "Indicates if the loan was defaulted (Yes/No)."
        tests:
          - accepted_values: ['Yes', 'No']
